[package]
name = "randomx"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
edition = "2018"

[dependencies]
sys = { package = "randomx-sys", version = "0.1", path = "sys" }

[workspace]
members = [
  "sys"
]