[package]
name = "randomx"
description = "Proof-of-work (PoW) algorithm that is optimized for general-purpose CPUs"
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
edition = "2018"

[dependencies]
sys = { package = "randomx-sys", version = "0.1", path = "sys" }

[workspace]
members = [
  "sys"
]