[package]
name = "randomx-sys"
description = "FFI bindings for RandomX"
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.50"
cmake = "0.1"